AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kinoman

  Sample SAM Template for kinoman

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  MessagesQueue:
    Type: AWS::SQS::Queue
  MovieDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: cache_key
          AttributeType: S
      KeySchema:
        - AttributeName: cache_key
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  EventSaverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: events.lambda_handler
      CodeUri: events/
      Runtime: ruby3.2
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref MovieDB
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt MovieDB.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MessagesQueue.Arn

  WebhooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          TG_TOKEN: '{{resolve:secretsmanager:CineScribeBot:SecretString:TG_TOKEN}}'
          TMDB_TOKEN: '{{resolve:secretsmanager:CineScribeBot:SecretString:TMDB_TOKEN}}'
          DYNAMODB_TABLE: !Ref MovieDB
          MESSAGES_QUEUE: !Ref MessagesQueue
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt MovieDB.Arn
            - Effect: "Allow"
              Action:
                - "sqs:SendMessage"
              Resource: !GetAtt MessagesQueue.Arn
    Metadata:
      DockerTag: ruby3.2-v1
      DockerContext: ./
      Dockerfile: app/Containerfile

Outputs:
  WebhooksURL:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WebhooksFunctionUrl.FunctionUrl
